# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1

jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:8.12

    steps:
      - checkout

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install npm wee
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

test:
  docker:
    - image: circleci/node:8.12

  steps:
    - checkout
    - run:
        name: Test
        command: npm test
    - run:
        name: Generate code coverage
        command: './node_modules/.bin/nyc report --reporter=text-lcov'
    - store_artifacts:
        path: test-results.xml
        prefix: tests
    - store_artifacts:
        path: coverage
        prefix: coverage
        
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master