# Javascript Node CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-javascript/ for more details
#
version: 2.1
orbs:
  status_to_ms_teams: 'bluemarblepayroll/status_to_ms_teams_pure_bash@dev:1.0.0'

jobs:
  build:
    working_directory: ~/repo

    docker:
      - image: circleci/node:8.12

    steps:
      - checkout

      - run:
          name: Update npm
          command: 'sudo npm install -g npm@latest'

      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}

      - run:
          name: Install npm wee
          command: npm install

      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - node_modules

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            # fallback to using the latest cache if no exact match is found
            - v1-dependencies-

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - status_to_ms_teams/report:
          webhook_url: ${MS_TEAMS_WEBHOOK_URL}

  test:
    docker:
      - image: circleci/node:8.12

    steps:
      - checkout

      - run:
          name: Install npm dev
          command: npm install --only=dev && npm install

      - run:
          name: Test
          command: npm test
      - run:
          name: ESLint
          command: eslint . -f junit -o ./reports/eslint/results.xml

      - store_test_results:
          path: reports

      - status_to_ms_teams/report:
          webhook_url: ${MS_TEAMS_WEBHOOK_URL}

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
#          filters:
#            branches:
#              only: master